### ISSUE TITLE
None of the “sha256” hashes in the integrity attribute match the content of the subresource.

### ISSUE THREAD

**Issue by John3** [Track3/hermit#1]
Hi,

I was trying you theme but it does not load properly.

`Hugo Static Site Generator v0.51 windows/amd64 BuildDate: 2018-11-07T10:11:06Z`

![image](https://user-images.githubusercontent.com/1057449/48735432-438a4f80-ec40-11e8-80c3-e30a8bacab07.png)

![image](https://user-images.githubusercontent.com/1057449/48735312-f1492e80-ec3f-11e8-89d7-88947b194527.png)

**Comment by Track3** [comment]
Thank you for trying my theme.
