### ISSUE TITLE
Add support for Table of Contents

### ISSUE THREAD

**Issue by Track3** [Track3/hermit#10]
I'd like to have automatically generated table of contents for blog posts, but find it hard to make the page looks right. So if anyone has ideas, feel free to let me know, thx!

Hugo docs: https://gohugo.io/content-management/toc/

My thinking is, only show ToC on large screens with it floating at right side of the content, there isn't too much point to display toc on a tiny screen, after all this theme is not made for extremely long geeky articles~

**Comment by chy373** [comment]
yes, it's nice to have a toc

**Comment by Track3** [comment]
The branch has merged, so this issue can be closed.

**Comment by shibumi** [comment]
Hi, how do I use the `toc`?
I have enabled toc in the header via `toc: true`, but I see no toc... is there any trick?

**Comment by lniwn** [comment]
> Hi, how do I use the `toc`?
> I have enabled toc in the header via `toc: true`, but I see no toc... is there any trick?

Click the trigger in the bottom bar
![image](https://user-images.githubusercontent.com/3256188/62259674-c73c4300-b441-11e9-8bfb-5ecbaed35762.png)

**Comment by shibumi** [comment]
@lniwn is there a way to enable the toc listing on default on the right? I think this 'click this first to see toc' is very inconvenient.

**Comment by lniwn** [comment]
> @lniwn is there a way to enable the toc listing on default on the right? I think this 'click this first to see toc' is very inconvenient.

#59
