### ISSUE TITLE
Title and subtitle disappear when page is zoomed to 500%

### ISSUE THREAD

**Issue by ffffansz** [Track3/hermit#107]
![image](https://user-images.githubusercontent.com/18579977/67630037-dc4b3580-f8bb-11e9-95ab-3092ee81dcdb.png)
Look at the picture above (from demo site).

This is a great theme, thank for the author and all contributors. 

Now I find a problem, when I apply it to my personal website, I zoom in and out the home page, which ensure everything about layout is good. In the picture above, you can see that when the home page is zoomed to 500%, the title disappears, and the the scroll bar of the browser has reached the top.

Hope the issue could be fixed.

**Comment by Track3** [comment]
Fixed by using “min-height: 100vh”, hope this won't cause any new issues.
