### ISSUE TITLE
Modifying Colour palette

### ISSUE THREAD

**Issue by JamesShiels** [Track3/hermit#13]
Firstly, Love the theme.

But I tried to do some small tweeking of the colour palette within the _predefined.css within the theme. Mainly just to do more personalisation of the site. Is this the correct place, as it does not seem to get populated out to the generated site?

**Comment by Track3** [comment]
Did you use Hugo extended version? Any modifications to scss will require extended version which has scss/sass built-in.

**Comment by JamesShiels** [comment]
thanks this worked for local work! I had some issues with the gitlab pages running this but have moved to just generating the public file locally for this! 

thanks!

**Comment by Track3** [comment]
You are welcome! You can try to commit your Hugo site's `resources` folder, in this way, it should be able to build with a standard version of Hugo.
