### ISSUE TITLE
Error with bottom bar in different languages

### ISSUE THREAD

**Issue by nachsommer** [Track3/hermit#17]
In the default configuration, the bottom bar displays the correct links to the subcatgories. However, if you switch to a different language, the links got confused with different subcategories merged into the path. E.g. if the link
http://localhost:1313/license/
does work well, the link in the german version looks like:
http://localhost:1313/de/literatur/lizenz
though it should look like
http://localhost:1313/de/lizenz
while another link should look like
http://localhost:1313/de/literatur/
Any idea why it is generated like this? Thanks for your help!

**Comment by Track3** [comment]
What's your configuration looks like? See Hugo docs: https://gohugo.io/content-management/multilingual/#menus

I just did some changes to adapt to multilingual mode, you can test it. 😊

**Comment by nachsommer** [comment]
Thanks for the quick answer! My configuration looks like this:


# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


# Configure the German version of the website.
[languages.de]
  languageCode = "de-de"
  contentDir = "content/de"
  #publishDir = "public/de"
title = "synapsen"

languageName = "Deutsch"
weight = 1

name = "synapsen"
homeSubtitle = "ein digitaler zettelkasten"

  [[languages.de.menu.main]]
    name = "Galerie"
    url = "gallery"
    weight = 10

  [[languages.de.menu.main]]
    name = "Laden"
    url = "laden"
    weight = 20

  [[languages.de.menu.main]]
    name = "Lizenz"
    url = "lizenz"
    weight = 30

  [[languages.de.menu.main]]
    name = "FAQ"
    url = "faq/"
    weight = 40

  [[languages.de.menu.main]]
    name = "Über"
    url = "about"
    weight = 50

  [[languages.de.menu.main]]
    name = "Literatur"
    url = "literatur"
    weight = 60

  [[languages.de.menu.main]]
    name = "🇬🇧"
    url = "/en"
    weight = 70


# Configure the English version of the website.
[languages.en]
languageCode = "en-us"
contentDir = "content/en"
#publishDir = "public/en"
title = "synapsen"
homeSubtitle = "a digital card index"

name = "synapsen"

weight = 0
languageName = "English"

[[languages.en.menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 10

[[languages.en.menu.main]]
    name = "Download"
    url = "/load"
    weight = 20

[[languages.en.menu.main]]
    name = "License"
    url = "/license/"
    weight = 30

[[languages.en.menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 40

[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

  [[languages.en.menu.main]]
    name = "References"
    url = "literature"
    weight = 60

[[languages.en.menu.main]]
	name = "🇩🇪" #
	url = "/de"
	#url = "../"
	weight = 70


And the result differs like this:

English original:



and the german version (n.b. it also has an instagram icon which I did not configure :-)



Thanks for checking it!

**Comment by nachsommer** [comment]
Just checked your changes. It works! Thank you so much. – The only thing: The instagram icon remains in the bar though I did not configure it. Any idea how to remove it?

**Comment by nachsommer** [comment]
No, not particularly. I only have configured this:

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:info@verzetteln.de"

  [[params.social]]
    name = "github"
    url = "https://github.com/nachsommer/synapsen"

And for some reason, the instagram icon shows up in the bar…

**Comment by Track3** [comment]
Is this all of the config for social icons? That's weird…

Try this command `hugo config | grep -i params` or `hugo config | FINDSTR /I params` if in Windows to check the full configuration.

**Comment by nachsommer** [comment]
Yes, that’s all of the config.
The result:

params = map[dateformshort:Jan 2 dateformnum:2006-01-02 justifycontent:false dateformnumtime:2006-01-02 15:04 -0700 footercopyright: &#183; synapsen version 4.3.8, 2018-12-16 dateform:Jan 2, 2006 bgimg:http://verzetteln.de/images/zk07.png homesubtitle:a digital card index social:[map[name:email url:mailto:info@verzetteln.de] map[defaultContentLanguageInSubdir:false name:github url:https://github.com/nachsommer/synapsen defaultContentLanguage:en]]]

**Comment by Track3** [comment]
I totally have no idea, and I can't reproduce this

**Comment by Track3** [comment]
OK, you can send me an email. [address here](https://www.xxxlbox.com/about/)

**Comment by Track3** [comment]
Problem solved.
