### ISSUE TITLE
Is there a method to generate the featuredImg over all pages?

### ISSUE THREAD

**Issue by duckie68** [Track3/hermit#2]
Or more specifically, the initial splash page?

**Comment by Track3** [comment]
Didn't plan to add any background images at first, then I realized setting a featured image as an almost invisible background could be interesting. 😂

That background is just a div with opacity set to `0.03`, it has already got a class `bg-img`. To set a background image for any page, you can just add this line to the specific template:

```html
<div class="bg-img" style="background-image: url('/path/to/background.png')"></div>
```

I'm planning to add a background image to the home splash page and make the image's url configurable.
