### ISSUE TITLE
Amazon link request

### ISSUE THREAD

**Issue by DemonTaz187** [Track3/hermit#23]
Hello. Can you add an amazon.com social link?

Or perhaps a custom link that can be added along with the social icons with a custom icon?

**Comment by Track3** [comment]
This theme uses [Feather icons](https://feathericons.com/). You can take a look at `hermit/layouts/partials/svg.html`, when this template is looped through, it will output one svg every time it get processed. You can modify or add any svgs here, for example, you can use font-awesome icons. If the `.name` matches, svg icons will get output.

Feather didn't provide the "Amazon" icon, so you have to do this by yourself, I'm planning to add some instructions to the readme about how to custom the theme.

**Comment by DemonTaz187** [comment]
Thanks for the pointer. I was able to add an amazon icon myself.
