### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by Fastbyte01** [Track3/hermit#39]
Hi, Would be a good idea to add pagination on the post list page, simply because if there are to much post the list is very long and can be very difficult to scroll through the page.

**Comment by Track3** [comment]
Originally, The post list is designed to be compact, it displays all of your post in one single page grouped by year, you can quickly jump to any position by using <kbd>Ctrl+F</kbd> to search, and you can't do that with pagination. Pagination can be less efficient sometimes.

For me, even without pagenation, 100 items in a single page is acceptable. I think lots of personal blogs won't have more that 100 posts. Of course, a single page may not be suitable for having too much blog posts, like hundreds/thousands of.

I'll leave this issue open to hear more people's opinion, and it will be nice to see someone who have done this can share some code with us.

**Comment by zemien** [comment]
I haven't managed to write more than 50 posts a year 😆  However, over time one could build up hundreds of post under one category/tag, and I believe the category/tag pages are based on the same template?

In general I agree pagination can be tricky. I would prefer work to go into a static site search capability.

**Comment by ruddra** [comment]
(*Maybe irrelevant*) Um, maybe its possible to add [headline links](https://github.com/Track3/hermit/issues/36) into the years in `/posts`. It will be much easier for you to share the posts if you have a lot of them.

**Comment by Track3** [comment]
@ruddra That's a good idea and it's actually very easy to do.

@zemien A search capability is pretty cool but it's a bit hard to do, I did plan to add a search function but I'm still not capable enough of doing it. I'll keep looking into that. As for dedicated templates for taxonomy page, actually I'm already working on it, just need some time.

**Comment by zemien** [comment]
Thanks for your continued efforts Track3!

I’m keen to implement some sort of static site searching so I will try a
few things and let you know how it goes.

**Comment by sheldonhull** [comment]
If suggest algolia and the instantsearch.js widget. This will provide best in class searching for atatic page for free and allow easy ui integration. 

Current example: sheldonhull.com

I'm migrating from Jekyll to Hugo and I think the only complicated part will be figuring out how to add to the header. I plan on floating the bar to the top and then adding the search icon there, but still learning Hugo so I haven't done this yet.

**Comment by zemien** [comment]
Sheldon

Algolia definitely works well on your site and probably mine too since
we're running personal free blogs. Businesses will have to pay for a
license, which means it shouldn't be baked  into the theme itself

Thanks for the recommendation

**Comment by Track3** [comment]
Algolia looks fine to me, I expect most people using this theme is non-commercially. `fuse.js` or `lunr.js` is also an option, but we can decide that later. For now, the first thing is to figure out the UI, I'm still not sure where to place that search form. Do we need a dedicated search page or put a search button in the header (bottom bar), or only add a search form in the `posts` page? I'm kinda busy these days…

**Comment by sheldonhull** [comment]
Sorry, not sure why it linked commit to my fork. Apologies. Still getting used to submodules. 

I can say that I've got the start of it working, just have to figure out how to generate the styled results. This could be possible to flip between lunr or algolia. I have the algolia index layout from another source generating the json, and another npm atomic-algolia that provides a nice way to generate content with deltas to reduce total io. 

Take a peek at https://www.sheldonhull.com and the searchbar I've copied from some other blogs posts with styling adjustments for this theme. Not fully there, but it's close to what I really wanted, the same type of page that https://mmistakes.github.io/minimal-mistakes/ uses, a toggle with integrated search. 

Tell me if you like the approach, I think once I figure out the results being populated the search overlay I am showing is a nice seamless way to do this without the need to have a dedicated search page.

**Comment by sheldonhull** [comment]
@zemien and yes, i agree. It should be an option, not forced. What I like about what I linked above, is that you create the UI overlay (you can see the half implemented one on my site right now at sheldonhull.com) and then you offer config option for search true/false, and searchProvider. Allow Lunr.js or Algolia, or something along those lines and then it just gets enabled. 

I'm not yet successful on populating the search page as other things came up, but definitely something i want to do. Will create a seperate issue and submit what I can if no one else can contribute their better javascript chops :-)

**Comment by angezanetti** [comment]
Hey there! I personally have a blog with 400+ posts, my blog is 10yo. So yeah, if someone wants to code a pagination system (by year maybe?) I would be glad :)
I don't really speak Go but I'll be happy to help!
