### ISSUE TITLE
Favicon issue with baseURL containing path.

### ISSUE THREAD

**Issue by VersBinarii** [Track3/hermit#41]
Hello,
Apologies if i'm missing something obvious.

The favicon get request always results in 404 if the baseURL is set to something like gitlab pages url.
i.e. https://user.gitlab.io/blog.
Page attempts to fetch the favicon from: https://user.gitlab.io/blog/blog/favicon-32x32.png.

Would you be able to offer some tips?

**Comment by Track3** [comment]
I test it with `baseURL` set to `https://user.gitlab.io/blog`, then the output is `/blog/favicon-32x32.png`. Relative urls start with a slash means it is relative to the root, so no matter what page you are in, `/blog/favicon-32x32.png` will always resolves to be `https://user.gitlab.io/blog/favicon-32x32.png`, this is correct.

I don't know why your setup didn't work, Did you changed any other configs or edited templates? Try to update Hugo and the theme to the newest version, and test with `hugo` command not `hugo server`, see the `public` folder.

**Comment by VersBinarii** [comment]
Very well. Thanks for confirming that this should be working. I must be doing something silly with my setup then.
