### ISSUE TITLE
Headers cause odd behaviour

### ISSUE THREAD

**Issue by groodle** [Track3/hermit#48]
Firstly, thanks for the great theme!

I have encountered an issue where I have used `## Header` format to create headers in my markdown.

I have created the following test page:
```
---
title: Test headers
date: 2019-02-13
published: true
---

Some tex to start the page.

## A Heading

some text after the heading
```

This causes the page to render with a huge svg:

![hugo-svg](https://user-images.githubusercontent.com/8886148/52715551-9e5bea80-2f94-11e9-997c-10c2ce38fabc.png)

This is the html that caused it:

```

<p>Some tex to start the page.</p>

<h2 id="a-heading">A Heading<a href="#a-heading" class="anchor" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 7h3a5 5 0 0 1 5 5 5 5 0 0 1-5 5h-3m-6 0H6a5 5 0 0 1-5-5 5 5 0 0 1 5-5h3"></path><line x1="8" y1="12" x2="16" y2="12"></line></svg></a></h2>

<p>some text after the heading</p>
```

Any help with this would be awesome!

**Comment by Track3** [comment]
That's probably because css didn't get updated. It is recommended to use Hugo extended version at local environment, so every time you preview your site locally, the `resources` folder in the root can be updated. Or, you can simply copy theme's `resources` folder to the site's root.

**Comment by groodle** [comment]
I followed your advice copied the `resources` directory from the theme into the site's root which solved the issue.

Thanks!
