### ISSUE TITLE
Adding "Tag" Menu

### ISSUE THREAD

**Issue by Funkyswing** [Track3/hermit#49]
Hello,

I am windering if we could add a tag menu in the homepage and show all the tags when we add them in the blogs. 

Thanks. :)

**Comment by Track3** [comment]
The "tags" page is already generated by default, just navigate to `/tags`, it lists all your tags. You can add the link to you menu with your config file.

For now, the `tags` page shares the same template with post list page, but to add a dedicated template for tags is already in the plan.

**Comment by Funkyswing** [comment]
> 
> 
> The "tags" page is already generated by default, just navigate to `/tags`, it lists all your tags. You can add the link to your menu with your config file.
> 
> For now, the `tags` page shares the same template with post list page, but to add a dedicated template for tags is already in the plan.

Thanks for answering.

As I am an amateur for coding, I would like to check if it is right to add this `url = "tags/"` in config file.

Thank you again.

**Comment by Track3** [comment]
Yes. Follow the example config:
https://github.com/Track3/hermit/blob/ad75aca5c2d4cd7a9919e990338125376c2d9658/exampleSite/config.toml#L66-L76
