### ISSUE TITLE
Hugo panics when _index.md is added under /posts/

### ISSUE THREAD

**Issue by onedrawingperday** [Track3/hermit#50]
Hello @Track3 

We are currently refactoring the content directory of the [HugoBasicExample](https://github.com/gohugoio/hugoBasicExample/tree/master/content) that is used in theme demos on the Hugo website.

Yesterday I committed an `_index.md` under the `post` section with the following content:

```
+++
aliases = ["posts","articles"]
+++
```

However your theme's demo no longer generates and in the console there is a panic:

````
1:57:30 AM:  ==== PROCESSING  hermit  ======
1:57:30 AM: Building site for theme hermit using its own exampleSite to ../themeSite/static/theme/hermit/
1:57:30 AM: panic: runtime error: index out of range
1:57:30 AM: goroutine 89 [running]:
1:57:30 AM: github.com/gohugoio/hugo/hugolib.(*Page).prepareData(0xc000278f00, 0xc000305880, 0x0, 0x0)
1:57:30 AM: 	/root/project/hugo/hugolib/page.go:1778 +0xf39
1:57:30 AM: github.com/gohugoio/hugo/hugolib.(*Site).preparePages(0xc000305880, 0x0, 0x0)
1:57:30 AM: 	/root/project/hugo/hugolib/site.go:1600 +0x132
1:57:30 AM: github.com/gohugoio/hugo/hugolib.(*Site).render(0xc000305880, 0xc000759900, 0x0, 0x0
1:57:30 AM: , 0x1)
1:57:30 AM: 	/root/project/hugo/hugolib/site.go:1076 +0x211
1:57:30 AM: github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc0000d6b00, 0xc000759900, 0xc0000d6b00, 0xc000718360)
1:57:30 AM: 	/root/project/hugo/hugolib/hugo_sites_build.go:302 +0x350
1:57:30 AM: github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc0000d6b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
1:57:30 AM: 	/root/project/hugo/hugolib/hugo_sites_build.go:97 +0x4ce
1:57:30 AM: github.com/gohugoio/hugo/commands.(*commandeer).buildSites(0xc0001400c0, 0x429932, 0x8)
1:57:30 AM: 	/root/project/hugo/commands/hugo.go:630 +0x79
1:57:30 AM: github.com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3(0x8, 0xfe2f98)
1:57:30 AM: 	/root/project/hugo/commands/hugo.go:305 +0x2a
1:57:30 AM: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000717800, 0xc000493250)
1:57:30 AM: 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:58 +0x57
1:57:30 AM: created by golang.org/x/sync/errgroup.(*Group).Go
1:57:30 AM: 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:55 +0x66
1:57:30 AM: FAILED to create exampleSite for hermit
````

I have looked into and tried adding more front matter like `date`, `title` just in case your theme requires these parameters but unfortunately I am unable to solve the problem.

Also note that this issue can be easily reproduced on your end. Simply add the `_index.md` under your post section in the exampleSite and execute `hugo server`.

Note that we really need to have the aliases of the post section in theme demos. Also your theme demo is the only one affected by this change as far as I can tell.

If you cannot find a solution feel free to open a topic at the Hugo Discussion Forum so that hopefully others can have a look at this.

Thanks.

cc: @digitalcraftsman

**Comment by onedrawingperday** [comment]
It seems that commit https://github.com/gohugoio/hugoBasicExample/commit/2941cdef6a905fdcaf1ee447a29986ff4feab5b5 fixed the problem.

Your theme's demo is live again over here: https://themes.gohugo.io/hermit/

Sorry for the noise.

**Comment by Track3** [comment]
I got this problem in my [blog](https://github.com/Track3/blog), too, which almost uses the same layout with this theme. With Hugo 0.53, `_index.md` under `content/posts/` just didn't take effect, then with Hugo 0.54, site could not build. I was so confused. Thanks to the information you provided, I now realize I have a misconfiguration.

I want to disable the `category` taxonomy and I did this in my `config.toml`:
```toml
[taxonomies]
  tag = "tags"
  category = ""
```

Turns out it's wrong, according to the [docs](https://gohugo.io/content-management/taxonomies#example-removing-default-taxonomies). The below is enough to override the default taxonomy:
```toml
[taxonomies]
  tag = "tags"
```

This theme's example config is also wrong and it's now fixed. I must say a big thanks to you and a big shoutout for your hardwork on the theme site.

**Comment by onedrawingperday** [comment]
The thing is that we need to have the category taxonomy in theme demos and that's why we have added and second config for taxonomies that is used in the Build Script.

Theme demos on the Hugo website since last month inherit their content from the HugoBasicExample contentDir and not from the exampleSite of each theme.

Anyway I will keep an eye to see if your theme's demo breaks again and I will let you know
