### ISSUE TITLE
break-all on links is not appropriate in all cases

### ISSUE THREAD

**Issue by r3domfox** [Track3/hermit#51]
In `style.scss`, links are set to `break-all`:

```scss
a {
      display: inline-block;
      border: 2px solid $text;
      border-radius: 5px;
      padding: 5px;
      transition-property: color, border-color;
      word-break: break-all;
```

This is desirable when the link text is the full URL, but not when it is some shorter text, i.e. when I have a labelled link:

```markdown
I want the words in [this link](http://example.com/some_long_url) formatted as normal text, not wrapped mid-word.
```

**Comment by Track3** [comment]
I find this only appears in buttons inside the 404 page, so it's not too bad, I'll remove it later.

**Comment by r3domfox** [comment]
You can see that the link text on this page, for example, is wrapped at non-word boundaries: https://thelastinstance.com/posts/post-imperial-wax-solvent/

**Comment by Track3** [comment]
OK, I see. Commit 61592cc6fb70d60bd60f02704117205464424833 has already fixed this, but in order to make css update, you need either use Hugo extended version in your build environment, or simply delete site root's `resources` folder and run hugo again to regenerate it.
