### ISSUE TITLE
time representation

### ISSUE THREAD

**Issue by peter-jerry-ye** [Track3/hermit#52]
Hi, I've just started using the Hugo and your theme. I've encountered the problem #27 . So it interests me how you represent time. I mean, the way you define now in the [param] isn't very clear for users (I prefer using yyyy/mm/dd instead of using a specific time(2016-01-02), like [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) in Java). What's more, it doesn't support i18n (or you didn't add it  #3). Any possibility to change it?

**Comment by Track3** [comment]
Hugo is written in Go, so it's kind of limited by what Go can offer. There's no way I can make this theme support the way that Java or PHP represent time, but you can see many examples at [Hugo documentation](https://gohugo.io/functions/format/#go-s-layout-string).

As for date format i18n, unfortunately Go does not yet have support for internationalized locales, but you can do it like [this](https://gohugo.io/content-management/multilingual/#customize-dates).

**Comment by peter-jerry-ye** [comment]
So it's the problem with Hugo. Okay, I see. Thanks for your reply.
