### ISSUE TITLE
Add cross origin integrity checking

### ISSUE THREAD

**Issue by gbochenek** [Track3/hermit#54]
When using this theme across multiple URLs, any integrity checking requires `crossorigin="anonymous"`, so all CSS and JS can be properly loaded.

**Comment by Track3** [comment]
I don't understand why using this theme across multiple URLs, if you really want to make your website able to be accessed across multiple URLs, you should use 301 or 302 redirects. Multiple URLs point to the same page content is bad for SEO. You should set one url as the baseURL, and then redirect other URLs to the baseURL.

**Comment by gbochenek** [comment]
You're right.  I was just being lazy here and will set up the proper redirects.

Thanks!
