### ISSUE TITLE
Archive link in 404 should be called Posts?

### ISSUE THREAD

**Issue by zemien** [Track3/hermit#55]
In the 404 layout there are two buttons Home and Archives.

https://github.com/Track3/hermit/blob/1da63e341b69d39ac830c488cc35fff70b833024/layouts/404.html#L11

I'm wondering if the Archives button should be called Posts, since by default it goes there anyway.

**Comment by Track3** [comment]
To my understanding, "archives" can stand for a page that lists all your blog posts, I think it's more like a general word, no matter what you call your blog posts page (like blog/writting…) it's all fine to use "archives". My English is not very good, so I might be wrong and I'm not very sure should we use "Posts" by default. But with Hugo i18n, it's really easy to override it, just edit the translations inside the `i18n` folder.

**Comment by zemien** [comment]
Hi

Your English is fine, don't worry. Yes your understanding of "archives" is
correct from word definition. My approach is to make the buttons consistent
if they're going to the same page.

I have not looked into i8n features so I will override from there. Thanks!
