### ISSUE TITLE
It's Wrong

### ISSUE THREAD

**Issue by Suremotoo** [Track3/hermit#6]
function "resources" not defined
![image](https://user-images.githubusercontent.com/26423989/49271484-d0d36c80-f4a8-11e8-87ff-cf28afaa006c.png)

**Comment by Track3** [comment]
This theme use Hugo Pipes to process scss, requires Hugo 0.43 or above. You should update.

**Comment by Suremotoo** [comment]
![image](https://user-images.githubusercontent.com/26423989/49322685-9f13e180-f54c-11e8-8c0d-87b350dda02d.png)
我用 brew reinstall hugo ，确实是0.43。  
extended 版是什么版，给 hugo 的 github 下载最新的包  0.52 ？？

**Comment by Track3** [comment]
brew应该可以升级包吧？其实你可以直接去[Hugo Release](https://github.com/gohugoio/hugo/releases)下载最新的二进制，丢进`/usr/local/bin`就能用

**Comment by Suremotoo** [comment]
Thanks, it's ok!   是版本的问题，但是 brew 里，hugo 版本是0.43 。
