### ISSUE TITLE
Disqus appears to be not working.

### ISSUE THREAD

**Issue by Skarlso** [Track3/hermit#60]
Hi.

Like the title says, I can't get disqus to work on my blog.

The site source is here: https://github.com/Skarlso/blogsource

The config is here: https://github.com/Skarlso/blogsource/blob/master/config.toml

I have disqus handle set and there appears to be nothing else required for it to work?

Yet on the site, there is no error, it just simply doesn't get loaded at all.

Cheers.

**Comment by Track3** [comment]
Hi, @Skarlso 

This theme has two templates for contents. For contents under `/content/posts` folder, the "/layouts/posts" template will be used, it will display date, tags and comments (if your `disqusShortname` is set in the config). Else will use the default template that comments is disabled by default, but you can add `comments: true` to the front matter to enable comments.

However, you can add `type: posts` to the front matter to make any post use the "posts" template.

**Comment by Skarlso** [comment]
Hi, @Track3!

Yay, that worked! `comments = true` in front matter. :))) Thanks!
