### ISSUE TITLE
Icons not rendering properly

### ISSUE THREAD

**Issue by jtnydv** [Track3/hermit#63]
SVG icons and fonts on windows are not rendering as they are supposed to render, refer to screenshots below.

Windows - https://i.imgur.com/AWcc1CD.png
Ubuntu 19.04 - https://i.imgur.com/xhIAxH0.png

**Comment by Track3** [comment]
That seems like a browser related issue. What browser are you using on Windows? Is there any errors in the devtools console? Or, maybe you can try to disable all browser extentions.
