### ISSUE TITLE
Add related content section in single post layout

### ISSUE THREAD

**Issue by jwon** [Track3/hermit#64]
Hello,

Just wanted to say that I'm a big fan of your theme! 👍 

I have a feature request: it would be great if hermit could support the related content feature as listed in the official Hugo docs:
https://gohugo.io/content-management/related/

Maybe providing a default implementation and allowing users to override the related content partial to customize it to their liking? That would be my preference!

Thank you so much!

**Comment by Track3** [comment]
Hi, @jwon 

I just opened that pull request (#77), please feel free to share your thoughts!

**Comment by jwon** [comment]
Wow, this is great! Thank you so much! I think this is enough to include as part of the theme and users can always override the partial if necessary.

**Comment by Track3** [comment]
Merged, close this for now.
