### ISSUE TITLE
Document how to change theme colors

### ISSUE THREAD

**Issue by fire** [Track3/hermit#66]
Can you add a readme section on how to change theme colours? It's scattered across the issue pages.

**Comment by marcosci** [comment]
Currently it also appears that the scss isn't recompiled after changing the colors in `_predefined.scss`, so a guide how to properly change the colors would be really useful.

**Comment by Track3** [comment]
README has been updated, hopefully it's well explained, any improvements are welcome:
https://github.com/Track3/hermit/blob/master/README.md#customize-css

**Comment by fire** [comment]
Works!
