### ISSUE TITLE
Add stackoverflow icon

### ISSUE THREAD

**Issue by ErikSchierboom** [Track3/hermit#68]
There are many social media icons available, but I'm missing a stackoverflow icon: https://stackoverflow.com/company/logos It would be great if this could be added.

**Comment by lkreimann** [comment]
I guess this is a great idea too, since Hugo and this theme is probably most used by developers for blogs/portfolios/websites. I would love that too. I know we can just override the theme, but this would be interesting for almost all the users of this theme I guess 👍

**Comment by Track3** [comment]
The problem is, the icon library this theme uses doesn't contain a stackoverflow icon and I'm not that capable to draw one…

This is as good as I can get.

**Comment by ErikSchierboom** [comment]
Which icon library is that if I may ask?

**Comment by Track3** [comment]
This theme uses [feather](https://github.com/feathericons/feather), I found an icon request in their issues but there's no further responses.

https://github.com/feathericons/feather/issues/231

**Comment by ErikSchierboom** [comment]
Thanks for the link! I'll close this issue and comment there.
