### ISSUE TITLE
Missing meta description

### ISSUE THREAD

**Issue by kscarlett** [Track3/hermit#69]
Am I missing something? I can't find how to set a description for the website/posts.

I know I could add this by overriding the page, but this seems quite essential?

**Comment by Track3** [comment]
Descriptions for the site can be set in the site's config file: https://github.com/Track3/hermit/blob/0101f8b8d9e1db41c07dac094dfe11e4610325a7/exampleSite/config.toml#L34-L37

Descriptions for a specific blog post can be set in the markdown file's front matter, basically
it's just a list of informations about this post, and it's right above the content. Add a "description" key, then the theme will pick the value and add a meta description tag. You can find examples here: 
https://gohugo.io/content-management/front-matter/#example

**Comment by kscarlett** [comment]
Thanks, just tried that and it works.

I initially thought that was a mistake in the example config, because the title is defined outside the params block.

**Comment by shibumi** [comment]
@Track3 Can I use `description` for meta description in blog posts, too?
