### ISSUE TITLE
add background image

### ISSUE THREAD

**Issue by pdwaggoner** [Track3/hermit#71]
Hi - sorry for another question. But I was wondering how to change the global background image for all pages. Specifically, how should I modify, `themes/hermit/layouts/_default/single.html`? Thanks!

**Comment by Track3** [comment]
Do you mean you want all normal single page using the global image set in site's config? If that's the case, you need to modify every `.Params.featuredImg` and `.Params.images` in `themes/hermit/layouts/_default/single.html` like so:

* `.Params.featuredImg` -> `.Site.Params.bgImg`
* `.Params.images` -> `.Site.Params.images`

This will turn all page level variables to site level. You can get the same results by add `images` or `featuredImg` filed to every single content file's front matter without modify the template.

**Comment by pdwaggoner** [comment]
I think this answers the question. Thanks for your response! I will give it a try.
