### ISSUE TITLE
Code Highlighting Broken in Ordered Lists

### ISSUE THREAD

**Issue by HeartAttackGorilla** [Track3/hermit#72]
I wrote an ordered list with a code block.

![blog-markdown](https://user-images.githubusercontent.com/50806960/58364517-abd21c00-7e83-11e9-8e00-da4b8990fc8c.PNG)

When it is rendered to the page it looks like this. The number after the code block is reset to one and indented.

![rendered-markdown](https://user-images.githubusercontent.com/50806960/58364629-4bdc7500-7e85-11e9-99cf-655b2986a7ec.PNG)

I attempted 4 extra spaces and a carriage return hoping it would work.

![eight-space-blog-markdown](https://user-images.githubusercontent.com/50806960/58364525-c73d2700-7e83-11e9-9ec6-d35e914831ba.PNG)

The back-ticks and programming language are all inside the box with no syntax highlighting.

![eight-space-markdown-rendered](https://user-images.githubusercontent.com/50806960/58364602-061fac80-7e85-11e9-8b46-496e84d83737.PNG)

**Is there a workaround to this issue?** If not I would be happy to try to fix the problem.

P.S. I know the code in the block doesn't make sense in this context. I was just testing stuff out.

**Comment by Track3** [comment]
With 4 spaces, if I remove language name, only use "```", the ordered list won't restart to one, but there is no syntax highlighting.

Then I tried Hugo `highlight` Shortcode, to my suprise, it works!

```markdown
1. item1
1. item2
{{< highlight javascript >}}
let x = 1;
console.log(x);
{{< / highlight >}}
1. item3
1. item4

---

1. item1
1. item2

{{< highlight javascript >}}
let x = 1;
console.log(x);
{{< / highlight >}}

1. item1
1. item2
```

<img width="567" alt="ss" src="https://user-images.githubusercontent.com/34504964/58380461-e81c8e00-7fe3-11e9-8ca6-5af8dcfc3d4d.png">

This is nothing to do with the theme, it's probably a bug of Hugo or maybe blackfriday or chroma.

**Comment by HeartAttackGorilla** [comment]
Thank you for the quick response! Yes the `highlight` shortcode works, but I wanted to avoid that. I found another solution.

Hugo uses two flavors of Markdown, `Blackfriday Project` and `Mmark` (which is a fork of Blackfriday Project).

* [Hugo Supported Content Formats](https://gohugo.io/content-management/formats/).

If I switch to `Mmark` everything renders as expected.

### Markdown

![mmark-markdown](https://user-images.githubusercontent.com/50806960/58385564-4172c600-7fc0-11e9-9466-7980cd17dadb.PNG)

### Rendered

![rendered-mmark-markdown](https://user-images.githubusercontent.com/50806960/58385565-43d52000-7fc0-11e9-995a-52ff34e396f2.PNG)

Thank you for your help, especially since this wasn't a problem with your theme.
