### ISSUE TITLE
Better behavior of auto-hide header in a mobile environment

### ISSUE THREAD

**Issue by astropenguin** [Track3/hermit#76]
Hi, I found that the site header is (unexpectedly) hidden when I scroll a page to the top and then the bounce-scroll occurs in a mobile environment (I encountered it at least on iOS).
This is because `window.pageYOffset` goes negative once and then back to zero, which is regarded as scroll-down by the `autoHideHeader` function of `main.js`.

If it is an unexpected behavior, I would like to propose to modify the function like:

```js
const autoHideHeader = () => {
  let currentScrollPosition = Math.max(window.pageYOffset, 0); // modified!
  if (currentScrollPosition > lastScrollPosition) {
    header.classList.remove('slideInUp');
    header.classList.add('slideOutDown');
  } else {
    header.classList.remove('slideOutDown');
    header.classList.add('slideInUp');
  }
  lastScrollPosition = currentScrollPosition;
}
```

Thanks!

**Comment by Track3** [comment]
Hi, @astropenguin :
That's definitely an unexpected behavior. I believe any browser that has that bounce back animation will potentially has this issue. The solution you provided looks really promising, feel free to submit an pull request, thanks!
