### ISSUE TITLE
Modify Hover behavior

### ISSUE THREAD

**Issue by shibumi** [Track3/hermit#82]
is there a way to modify the hover behavior? for example pinning it at the top instead of the bottom? I am not really a fan of the hover at all.. I would prefer just a static link header on the top..
but sadly I am not a web designer.. any idea how I can accomplish this?

It would be nice to have an option for disabling the hover bar and having a static header at the top instead. Something like this on my current website: https://nullday.de/

(just without that left logo and right dark/light theme switcher of course)

The reason why i want to change from hello-friend-ng to hermit, is that hermit is blazing fast and hello-friend-ng got so bloated recently that it destroys my good google pagespeed ranking

**Comment by Track3** [comment]
To pin it to the top is very easy, the harder part is to adjust everything else. "Pinned to the top" and "Hovered at the bottom" are totally different page layouts. As you can see, in the original theme, the height of single page's title is not fixed, based on the page width, the height is different. If we pin the header to the top, this has to be adjusted. What's more, animations has to be removed, javascript that related to page scroll event has to be modified and mobile menu behaviour has to be changed as well.

It will be very difficult to support both at the same time.  Sometimes we just have to choose one!

**Comment by shibumi** [comment]
I see, so it's far more complicated when I thought. (I am not a web-guy, so sorry for stealing your time with this issue) :)
