### ISSUE TITLE
disqus error in production

### ISSUE THREAD

**Issue by Mosaab4** [Track3/hermit#9]
I'm trying to activate disqus comments for blog posts, it works correctly in development, but when try to deploy the site it gave me this error 

`Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:48:5: executing "main" at <partialCached "disqu...>: error calling partialCached: "/opt/build/repo/themes/hermit/layouts/partials/disqus.html:10:36": execute of template failed: template: partials/disqus.html:10:36: executing "partials/disqus.html" at <.Site.DisqusShortnam...>: can't evaluate field Site in type string`

also there's styling matter you would deal with:
the width of the panel of disqus is wider than the post, you may restyle it to be more beautiful

![screenshot of the disqus comment in the single post](https://user-images.githubusercontent.com/20595561/49758980-00fce580-fcc9-11e8-9ae0-5f16cf38f7f9.png)

**Comment by Track3** [comment]
This should now be fixed. More styles may still need to be added.

**Comment by mnunes** [comment]
Wow! I updated the theme and changed my folder name and I got tags, disqus and some statistics inside my posts. Very cool!

Thanks a lot.
