### ISSUE TITLE
Option About Mode Button And Top Navigation Menu

### ISSUE THREAD

**Issue by BayuAngora** [Track3/hermit#90]
I like the theme because it's simple and lightweight. It would be great if there's a dark mode button and option to choose navigation menu position, so we can choose navigation menu position on top or bottom via config.

**Comment by Track3** [comment]
For the dark mode toggle, issue #99 already requested this, will add this feature.

Adding anoption about  navigation bar position is also requested many times, but as I said in #82, it will be difficult to maintain 2 layouts at the sametime, so won't focus on adding it at the moment. Will close this issue for now.
